export enum SymbolName {
    BAR = 'bar',
    BELL = 'bell',
    BUDOU = 'budou',
    CHERRY = 'cherry',
    PIERO = 'piero',
    RED_7 = 'red_7',
    REPLAY = 'replay',
}

export enum ReelPosition {
    LEFT = 0,
    CENTER = 1,
    RIGHT = 2
}

export const SYMBOL_HEIGHT=111;

export const SYMBOL_LIST: SymbolName[][] = [
    [
        SymbolName.BELL,
        SymbolName.RED_7,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.CHERRY,
        SymbolName.BELL,
        SymbolName.PIERO,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
        SymbolName.BAR,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
        SymbolName.PIERO,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.CHERRY
    ],
    [
        SymbolName.REPLAY,
        SymbolName.RED_7,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
        SymbolName.REPLAY,
        SymbolName.PIERO,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
        SymbolName.REPLAY,
        SymbolName.BAR,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
        SymbolName.REPLAY,
        SymbolName.PIERO,
        SymbolName.BUDOU,
        SymbolName.BELL,
        SymbolName.CHERRY,
    ],
    [
        SymbolName.BUDOU,
        SymbolName.RED_7,
        SymbolName.BAR,
        SymbolName.BELL,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.CHERRY,
        SymbolName.PIERO,
        SymbolName.BELL,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.CHERRY,
        SymbolName.PIERO,
        SymbolName.BELL,
        SymbolName.REPLAY,
        SymbolName.BUDOU,
        SymbolName.CHERRY,
        SymbolName.PIERO,
        SymbolName.BELL,
        SymbolName.REPLAY,
    ],
]